[[macOSSDK]]
arch = "x86_64"
git-tree-sha1 = "77e16878e963b51f8661d064c1024422b1a6eeea"
os = "macos"

    [[macOSSDK.download]]
    sha256 = "f911711fb162217e8107d81196e027d9246dbf298947bfaf87ccae351b7b6074"
    url = "https://github.com/staticfloat/macOSSDK_jll.jl/releases/download/v11.1.0/macOSSDK-v11.1.0-x86_64-apple-darwin.tar.gz"
[[macOSSDK]]
arch = "aarch64"
git-tree-sha1 = "77e16878e963b51f8661d064c1024422b1a6eeea"
os = "macos"

    [[macOSSDK.download]]
    sha256 = "f911711fb162217e8107d81196e027d9246dbf298947bfaf87ccae351b7b6074"
    url = "https://github.com/staticfloat/macOSSDK_jll.jl/releases/download/v11.1.0/macOSSDK-v11.1.0-aarch64-apple-darwin.tar.gz"

[[macOSSDK-build_log]]
arch = "x86_64"
git-tree-sha1 = "8d504b731b0048dd3f2195d273c9a5b66739b023"
lazy = true
os = "macos"

    [[macOSSDK-build_log.download]]
    sha256 = "6d4ceaab1bd19a4c4593145fefc955629389db49885276f13353167f831cf566"
    url = "https://github.com/staticfloat/macOSSDK_jll.jl/releases/download/v11.1.0/macOSSDK-build_log-v11.1.0-x86_64-apple-darwin.tar.gz"
[[macOSSDK-build_log]]
arch = "aarch64"
git-tree-sha1 = "f22a55206c10b15fb261c009bc065eb82dc4dbe8"
lazy = true
os = "macos"

    [[macOSSDK-build_log.download]]
    sha256 = "0ce4873c3441b383259ab5cca5aca8d91a41c6937025f582b9a9f91cbd652fdf"
    url = "https://github.com/staticfloat/macOSSDK_jll.jl/releases/download/v11.1.0/macOSSDK-build_log-v11.1.0-aarch64-apple-darwin.tar.gz"

[[macOSSDK-extract_log]]
arch = "x86_64"
git-tree-sha1 = "7cd5859440f38609e590866571822f3587b97e00"
lazy = true
os = "macos"

    [[macOSSDK-extract_log.download]]
    sha256 = "9dc94e43e85558b5fdaecc12eeb1dd21adab78da857c9b4c4680aec060aad075"
    url = "https://github.com/staticfloat/macOSSDK_jll.jl/releases/download/v11.1.0/macOSSDK-extract_log-v11.1.0-x86_64-apple-darwin.tar.gz"
[[macOSSDK-extract_log]]
arch = "aarch64"
git-tree-sha1 = "d1bd26b24df2b2b5e9ac32ddc303f15e10ad4c9a"
lazy = true
os = "macos"

    [[macOSSDK-extract_log.download]]
    sha256 = "196c7999dc6df623739e0da378c7a38ac3843f7936f05ca9e7a2853175966442"
    url = "https://github.com/staticfloat/macOSSDK_jll.jl/releases/download/v11.1.0/macOSSDK-extract_log-v11.1.0-aarch64-apple-darwin.tar.gz"
