[[macOSSDK]]
arch = "x86_64"
git-tree-sha1 = "77e16878e963b51f8661d064c1024422b1a6eeea"
os = "macos"

    [[macOSSDK.download]]
    sha256 = "38b8f861bb19d796ef3c26cff23da3db7d03916cf89d37bcc93129789f64ee6b"
    url = "https://github.com/staticfloat/macOSSDK_jll.jl/releases/download/v11.1.1/macOSSDK-v11.1.1-x86_64-apple-darwin.tar.gz"
[[macOSSDK]]
arch = "aarch64"
git-tree-sha1 = "77e16878e963b51f8661d064c1024422b1a6eeea"
os = "macos"

    [[macOSSDK.download]]
    sha256 = "38b8f861bb19d796ef3c26cff23da3db7d03916cf89d37bcc93129789f64ee6b"
    url = "https://github.com/staticfloat/macOSSDK_jll.jl/releases/download/v11.1.1/macOSSDK-v11.1.1-aarch64-apple-darwin.tar.gz"

[[macOSSDK-build_log]]
arch = "x86_64"
git-tree-sha1 = "c21de90eb49c3dbfb91d6bff2b2fef602ff3c48d"
lazy = true
os = "macos"

    [[macOSSDK-build_log.download]]
    sha256 = "f133afc24e8a889a4a73bf9ddc05c075639249de7a73f0ac7cd0e80fba06ce22"
    url = "https://github.com/staticfloat/macOSSDK_jll.jl/releases/download/v11.1.1/macOSSDK-build_log-v11.1.1-x86_64-apple-darwin.tar.gz"
[[macOSSDK-build_log]]
arch = "aarch64"
git-tree-sha1 = "b7c4f1b05addf7f2b96bea0332d63f9a4cfa96e6"
lazy = true
os = "macos"

    [[macOSSDK-build_log.download]]
    sha256 = "a22cacb47f40074f3fce85c7934070e9e8ba599af4bf42949e351ce539a415c1"
    url = "https://github.com/staticfloat/macOSSDK_jll.jl/releases/download/v11.1.1/macOSSDK-build_log-v11.1.1-aarch64-apple-darwin.tar.gz"

[[macOSSDK-extract_log]]
arch = "x86_64"
git-tree-sha1 = "e2ffff054bf5b43a637ce72c467b21fae3519dc1"
lazy = true
os = "macos"

    [[macOSSDK-extract_log.download]]
    sha256 = "9112887956d00f020c2356ff4e365344f2e7e9073fc2e1e4cfde58ad323f0049"
    url = "https://github.com/staticfloat/macOSSDK_jll.jl/releases/download/v11.1.1/macOSSDK-extract_log-v11.1.1-x86_64-apple-darwin.tar.gz"
[[macOSSDK-extract_log]]
arch = "aarch64"
git-tree-sha1 = "840fb7cee3649bc9d06881623ae9056b1a0adb30"
lazy = true
os = "macos"

    [[macOSSDK-extract_log.download]]
    sha256 = "0a2d7cb4c692f87d24f394e316ec6296e106ff0b50a395eccc8dca1719b71086"
    url = "https://github.com/staticfloat/macOSSDK_jll.jl/releases/download/v11.1.1/macOSSDK-extract_log-v11.1.1-aarch64-apple-darwin.tar.gz"
