[[macOSSDK]]
arch = "x86_64"
git-tree-sha1 = "77e16878e963b51f8661d064c1024422b1a6eeea"
os = "macos"
os_version = "20.0.0"

    [[macOSSDK.download]]
    sha256 = "36c25d337560df3e4bd3d4dcebe9af9faadfe0efbf3dc35d522d1315eae505bf"
    url = "https://github.com/staticfloat/macOSSDK_jll.jl/releases/download/v11.1.1-GCCBootstrap-x86_64-linux-gnu/macOSSDK-v11.1.1-x86_64-apple-darwin20.tar.gz"
[[macOSSDK]]
arch = "aarch64"
git-tree-sha1 = "77e16878e963b51f8661d064c1024422b1a6eeea"
os = "macos"
os_version = "20.0.0"

    [[macOSSDK.download]]
    sha256 = "36c25d337560df3e4bd3d4dcebe9af9faadfe0efbf3dc35d522d1315eae505bf"
    url = "https://github.com/staticfloat/macOSSDK_jll.jl/releases/download/v11.1.1-GCCBootstrap-x86_64-linux-gnu/macOSSDK-v11.1.1-aarch64-apple-darwin20.tar.gz"

[[macOSSDK-build_log]]
arch = "x86_64"
git-tree-sha1 = "7e0083b4546c816d927ce8087df2a015791e6a91"
lazy = true
os = "macos"
os_version = "20.0.0"

    [[macOSSDK-build_log.download]]
    sha256 = "9a33d5d9b10bc00b8595b0e6eb2d8dca7a4ff83391d2219fe1fc15164d4af633"
    url = "https://github.com/staticfloat/macOSSDK_jll.jl/releases/download/v11.1.1-GCCBootstrap-x86_64-linux-gnu/macOSSDK-build_log-v11.1.1-x86_64-apple-darwin20.tar.gz"
[[macOSSDK-build_log]]
arch = "aarch64"
git-tree-sha1 = "116a8b6ee819f7bde6df864c0f0d80d97f26926a"
lazy = true
os = "macos"
os_version = "20.0.0"

    [[macOSSDK-build_log.download]]
    sha256 = "953fca83f8a084b8f0a6892e1ced508d1655ace294a49dbb5dcafa23a28a548b"
    url = "https://github.com/staticfloat/macOSSDK_jll.jl/releases/download/v11.1.1-GCCBootstrap-x86_64-linux-gnu/macOSSDK-build_log-v11.1.1-aarch64-apple-darwin20.tar.gz"

[[macOSSDK-extract_log]]
arch = "x86_64"
git-tree-sha1 = "e025308d946b9a46af9cd542090033166ebbd6eb"
lazy = true
os = "macos"
os_version = "20.0.0"

    [[macOSSDK-extract_log.download]]
    sha256 = "9f6e8b5209442d5604c5b48e1a65b1a8247395974bc72b67aff305dec9a4db8d"
    url = "https://github.com/staticfloat/macOSSDK_jll.jl/releases/download/v11.1.1-GCCBootstrap-x86_64-linux-gnu/macOSSDK-extract_log-v11.1.1-x86_64-apple-darwin20.tar.gz"
[[macOSSDK-extract_log]]
arch = "aarch64"
git-tree-sha1 = "70c1c0d7b67ebcf2398c5033584a83b531d45c10"
lazy = true
os = "macos"
os_version = "20.0.0"

    [[macOSSDK-extract_log.download]]
    sha256 = "c4e3101de4c06879b460c208245d96c5c2f497d3fea8e936a64f34960c687759"
    url = "https://github.com/staticfloat/macOSSDK_jll.jl/releases/download/v11.1.1-GCCBootstrap-x86_64-linux-gnu/macOSSDK-extract_log-v11.1.1-aarch64-apple-darwin20.tar.gz"
