[[macOSSDK]]
arch = "x86_64"
git-tree-sha1 = "77e16878e963b51f8661d064c1024422b1a6eeea"
os = "macos"
os_version = "20.0.0"

    [[macOSSDK.download]]
    sha256 = "24ceb47ea693aa68c80055421e16e9017e285231321659bbe6a95daa5ac039a9"
    url = "https://github.com/staticfloat/macOSSDK_jll.jl/releases/download/v11.1.1-GCCBootstrap-x86_64-linux-gnu/macOSSDK-v11.1.1-x86_64-apple-darwin20.tar.gz"
[[macOSSDK]]
arch = "aarch64"
git-tree-sha1 = "77e16878e963b51f8661d064c1024422b1a6eeea"
os = "macos"
os_version = "20.0.0"

    [[macOSSDK.download]]
    sha256 = "24ceb47ea693aa68c80055421e16e9017e285231321659bbe6a95daa5ac039a9"
    url = "https://github.com/staticfloat/macOSSDK_jll.jl/releases/download/v11.1.1-GCCBootstrap-x86_64-linux-gnu/macOSSDK-v11.1.1-aarch64-apple-darwin20.tar.gz"

[[macOSSDK-build_log]]
arch = "x86_64"
git-tree-sha1 = "b3313a12fc19cc1c4aed2942a7ef58df327ba3ad"
lazy = true
os = "macos"
os_version = "20.0.0"

    [[macOSSDK-build_log.download]]
    sha256 = "e3b910db0b5993ac6f40c118db3ee898af68fd6b04f256f01ca6b70cff3e9beb"
    url = "https://github.com/staticfloat/macOSSDK_jll.jl/releases/download/v11.1.1-GCCBootstrap-x86_64-linux-gnu/macOSSDK-build_log-v11.1.1-x86_64-apple-darwin20.tar.gz"
[[macOSSDK-build_log]]
arch = "aarch64"
git-tree-sha1 = "bdd81eb47cfb20b5a518431c4fe7ff2f392a50fc"
lazy = true
os = "macos"
os_version = "20.0.0"

    [[macOSSDK-build_log.download]]
    sha256 = "51a9f344120654bcea211e5eb24a7ea853df83311580b4623ff5282a1684149e"
    url = "https://github.com/staticfloat/macOSSDK_jll.jl/releases/download/v11.1.1-GCCBootstrap-x86_64-linux-gnu/macOSSDK-build_log-v11.1.1-aarch64-apple-darwin20.tar.gz"

[[macOSSDK-extract_log]]
arch = "x86_64"
git-tree-sha1 = "d26ade6208f6a45e52ab107dcca68fb5aadff9b7"
lazy = true
os = "macos"
os_version = "20.0.0"

    [[macOSSDK-extract_log.download]]
    sha256 = "8b385c905934349b37e333bf3400896bdfe46de01a1cfb22b2b6c99933c74433"
    url = "https://github.com/staticfloat/macOSSDK_jll.jl/releases/download/v11.1.1-GCCBootstrap-x86_64-linux-gnu/macOSSDK-extract_log-v11.1.1-x86_64-apple-darwin20.tar.gz"
[[macOSSDK-extract_log]]
arch = "aarch64"
git-tree-sha1 = "bb13ebbc6ccbc55e2a757485eb984b628ac30e38"
lazy = true
os = "macos"
os_version = "20.0.0"

    [[macOSSDK-extract_log.download]]
    sha256 = "bfd89f428f9889d043c234a49c184a460db3b0ba8ebabcac3d52edba1e0e6c8b"
    url = "https://github.com/staticfloat/macOSSDK_jll.jl/releases/download/v11.1.1-GCCBootstrap-x86_64-linux-gnu/macOSSDK-extract_log-v11.1.1-aarch64-apple-darwin20.tar.gz"
